on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Set vars for build only if not on main"
        run: |
          echo "PAGES_BRANCH=test-pages" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      - name: "Set vars for deploy if on main"
        run: |
          echo "PAGES_BRANCH=gh-pages" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'
      - name: 'Install cargo'
        run: sudo apt-get install -qy cargo
      - name: "Cache cargo"
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo
      - name: 'Install mdbook'
        run: cargo install --locked mdbook mdbook-tabs mdbook-svgbob
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          path: 'guide'
      - name: 'Checkout acton repo'
        uses: actions/checkout@master
        with:
          repository: 'actonlang/acton'
          path: 'acton'
          token: ${{ secrets.ACTBOT_PAT }}
      - name: 'Build acton-by-example'
        run: |
          export PATH=/.cargo/bin:$PATH
          cd acton/docs/acton-by-example
          mdbook build -d ../../../guide-build
      - name: "Configure git"
        run: |
          cd guide
          git config --global --add safe.directory /__w/acton.guide
          git config user.name "Web Bot"
          git config user.email web@acton-lang.org
      - name: "Create gh-pages branch from scratch"
        run: |
          cd guide
          cp -av ../guide-build/. .
          echo "acton.guide" > CNAME
          git status
          git checkout --orphan gh-pages
          git add .
          git status
          git commit -a -m "Publish web page"
          git push --force origin gh-pages
